apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx
  labels:
    {{ include "frontend.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html/src/pages;
        index index.html;

        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript;

        location /css/ {
            alias /usr/share/nginx/html/src/css/;
        }

        location /js/ {
            alias /usr/share/nginx/html/src/js/;
        }

        location /assets/ {
            alias /usr/share/nginx/html/src/assets/;
        }

        location /api/ {
            proxy_pass http://{{ .Values.backendHost }}:{{ .Values.backendPort }}/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
