apiVersion: v2
name: frontend
description: Nginx static web server serving the Bushido Brand storefront
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: DevSecOps Team
    email: devsecops-team@bushidobrand.com
