apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bushido-brand-db
  namespace: argocd
  labels:
    project: bushido-brand
    tier: database
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bushido-brand
  source:
    repoURL: https://github.com/HamzaMaLik121/bushido-brand-app-.git
    targetRevision: main
    path: bushido-brand-pipeline/gitops-repo/charts/db
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: bushido-brand
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
